MyFinancial/www/MyFinancial/MyFinancial/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFinancial.Controllers
{
    public class DefaultController : Controller
    {
        //
        // GET: /Default/

        public ActionResult Default()
        {
            //ViewBag.Views = "Đây là trang chủ của MyFinancial";
           
            return View();
        }

        public ActionResult TinKinhTe()
        {
            return View();
        }

        public ActionResult SoThuChi()
        {
            return View();
        }

        public ActionResult TuVanChiTieu()
        {
            return View();
        }

        public ActionResult TinKhuyenMai()
        {
            return View();
        }

        public ActionResult BangXepHang()
        {
            return View();
        }

        public ActionResult TrangChu()
        {
            return View();
        }

        public ActionResult GhiChep()
        {
            return View();
        }

        public ActionResult TinhHinhThuChi()
        {
            return View();
        }

        public ActionResult PhanTichChiTieu()
        {
            return View();
        }

        public ActionResult GioiThieu()
        {
            return View();
        }

        public ActionResult LienHe()
        {
            return View();
        }

        public ActionResult DangKi()
        {
            return View();
        }

        public ActionResult Poster()
        {
            return View();
        }

        
    }
}

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/BangXepHang.cshtml
@{
    ViewBag.Title = "BangXepHang";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>BangXepHang</h2>
<p>Danh sách những thành viên nổi bật trong tháng.</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/DangKi.cshtml
@{
    ViewBag.Title = "DangKi";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>DangKi</h2>
<p>Đăng kí tài khoản tại đây.</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")
<div class="box-tin"></div>

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/Default.cshtml
@{
    ViewBag.Title = "Default";
    Layout = "~/Views/Shared/Default.cshtml";
}
@section featured {
    <section class="featured">
        
<link href="~/Content/ddlevelsmenu-topbar.css" rel="stylesheet" />
<script src="~/Scripts/ddlevelsmenu.js"></script>


<div class="content-left">
    <div class="box-home6">
        @Html.ActionLink("Tham gia ngay!","DangKi","Default")
       
    </div>
    <div class="box-home1"> 
        <div class="tieude1">
            <h2>@Html.ActionLink("Sổ thu chi của bạn","SoThuChi","Default")</h2>
        </div>
    </div>
    <div class="box-home2">
        <div class="tieude1">
            <h2>@Html.ActionLink("Tin kinh tế","TinKinhTe","Default")</h2>
            </div>
    </div>
    <div class="box-home3">
        <div class="tieude1">
            <h2>@Html.ActionLink("Tư vấn chi tiêu","TuVanChiTieu","Default")</h2>
            </div>
    </div>
    <div class="box-home4">
        <div class="tieude1">
        <h2>@Html.ActionLink("Tin khuyến mãi","TinKhuyenMai","Default")</h2>
            </div>
    </div>
    
</div>
            
        </section>
    }



   

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/GhiChep.cshtml
@{
    ViewBag.Title = "GhiChep";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>GhiChep</h2>
<p>Sổ chi chép thu chi cá nhân.</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/GioiThieu.cshtml
@{
    ViewBag.Title = "GioiThieu";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>GioiThieu</h2>
<p>Giới thiệu</p>
@Html.ActionLink("Quay lại trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/LienHe.cshtml
@{
    ViewBag.Title = "LienHe";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>LienHe</h2>
<p>Thông tin liên hệ.</p>
@Html.ActionLink("Quay lại trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/PhanTichChiTieu.cshtml
@{
    ViewBag.Title = "PhanTichChiTieu";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>PhanTichChiTieu</h2>
<p>Phân tích tình hình thu chi của bạn.</p>
@Html.ActionLink("Quay lại trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/Poster.cshtml
@{
    ViewBag.Title = "Poster";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>Poster</h2>
@Html.ActionLink("Quay về trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/SoThuChi.cshtml
@{
    ViewBag.Title = "SoThuChi";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>SoThuChi</h2>
<p>Sổ thu chi của bạn tại đây.</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/TinKhuyenMai.cshtml
@{
    ViewBag.Title = "TinKhuyenMai";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>TinKhuyenMai</h2>
<p>Thông tin khuyến mãi, giảm giá.</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/TinKinhTe.cshtml
@{
    ViewBag.Title = "TinKinhTe";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>TinKinhTe</h2>
<p>Đây là nội dung trang TinKinhTe</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")
<div class="box-tin"></div>

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/TinhHinhThuChi.cshtml
@{
    ViewBag.Title = "TinhHinhThuChi";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>TinhHinhThuChi</h2>
<p>Tình hình thu chi</p>
@Html.ActionLink("Quay lại trang chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>TrangChu</h2>
@Html.ActionLink("Trang Chủ","Default","Default")

MyFinancial/www/MyFinancial/MyFinancial/Views/Default/TuVanChiTieu.cshtml
@{
    ViewBag.Title = "TuVanChiTieu";
    Layout = "~/Views/Shared/Default.cshtml";
}

<h2>TuVanChiTieu</h2>
<p>Tư vấn tình hình thu chi của bạn.</p>
@Html.ActionLink("Quay về trang chủ","Default","Default")